### ISSUE TITLE
[Feature-Request]: Acceleration and Gravity multiplier adjustable by percentage

### ISSUE THREAD

**Issue by Scape070** [ForzaMods/AIO#102]
### Game

FH5

### What feature are you requesting?

Ability to also set percentage when increasing/decreasing acceleration and gravity. I use this tool to balance the drivatars in offline races and make them playable and enjoyable again, without the drivatars being way too fast or way too slow, just in the sweet spot. Currently the multipliers only go up/down by 0,1 for acceleration and 1 for gravity, which makes it hard to find the sweet spot and usually ends up making you too fast or too slow again, albeit less extreme than Forza Horizon 5's broken difficulties. I could just manually change the numbers by typing them in, but this is just too much work to accurately find the "sweet spot" and requires me to use a calculator everytime I play.

I don't want the current multipliers (up/down arrows, typing in numbers) to disappear. I just want the ability to also be able to use percentage for increasing/decreasing the acceleration/gravity values.

**Comment by szaaamerik** [comment]
@Yeethan69 Thoughts?

**Comment by szaaamerik** [comment]
not planned
