### ISSUE TITLE
I'm using windows Xbox version of game and will not work

### ISSUE THREAD

**Issue by camolot13** [ForzaMods/AIO#103]
All I want is free cars wheelspins or credits any will do. but I cant get any of them to work on the pc Xbox version of Forza 5. I would prefer not to buy it on steam because I get it free with the Xbox Game Pass.

**Comment by quiet69** [comment]
The tool works and was primarily developed for the xbox version of the game. refresh/restart the tool and game. try joining the discord server for more help

**Comment by Jesse9418** [comment]
All I want is all cars in game x5 and max money in fh4

**Comment by Jesse9418** [comment]
And wheelspins max
