### ISSUE TITLE
[Feature-Request]: Could someone explain the meaning of these parameters in the screenshot?

### ISSUE THREAD

**Issue by christensennn** [ForzaMods/AIO#108]
### Game

FH5

### What feature are you requesting?

![image](https://user-images.githubusercontent.com/42790204/187574749-736601e2-1b9c-4695-b7a1-65d972cd4627.png)

For example, shown in the screenshot, I randomly set the parameters in the Turn Assist blocks, and click the Turn assist toggle. However, when I am back to the game, I can't find any difference when I am driving, whether I set auto-steering on or off.

So, can someone explain the exact meaning of these parameters(including those in Wheelspeed Hack), or just tell me how to make it works correctly? Thank you.

**Comment by chungnut** [comment]
its not working wait for update

**Comment by szaaamerik** [comment]
![image](https://github.com/ForzaMods/AIO/assets/126014478/1d415d60-0dc9-47ed-9c57-c7bf570fdeef)
