### ISSUE TITLE
[Bug]: Add all cars, add rare cars, free performance upgrades not working with latest version of FH5 (1.507.426)

### ISSUE THREAD

**Issue by registergithubusername** [ForzaMods/AIO#114]
### What version of the aio were you running?

0.0.0.50

### Game

FH5

### Game Version

Cracked (online-fix)

### What is the bug?

FH5 version 1.507.426HV (no idea what HV means but had that on the end for several releases!)

AIO 0.0.0.50

- Have car pass
- connected to internet
- W11 Pro, steam version of FH5
- El amigos version with latest InsameRemzez patch, using online-fix.

Tried several times to add all cars, rare cars and free performance upgrades, none of those 3 are working since new FH5 1.507.426 release. Worked flawlessly on the previous version of FH5.

Also, of note show all cars and make all cars free in autoshow is still working even with the latest version (1.507.426) of FH5 so it appears that it may be something distinct to the process that takes place when the tuning save is initiated. 

Hope the above information is useful.

**Comment by 520299XX** [comment]
Are there any other tools for Horizon 5 one click brushing the whole car
