### ISSUE TITLE
FH4 Stuck Loading

### ISSUE THREAD

**Issue by segg21** [ForzaMods/AIO#116]
### What version of the aio were you running?

0.0.0.50

### Game

FH4

### Game Version

Microsoft store

### What is the bug?

I’ve replicated this numerous times and always been the successful.

- Add all cars to autoshow, and make free to buy
- Enter Garage (From Outside)
- Buy a car
- Leave Garage (To Outside)
- Turn off all and free cars
- Go back in Garage (From Outside)

The issue is when you go select a car (doesn’t matter which or where from), the game would start camera previewing the car but would never load to next scene. It would be stuck like this with no way out, besides restarting the entire game.

Any work around or fix? I noticed AIO hasn’t been updated since August and can’t find similar issues that I’m having.

Thhxxxx!!

**Comment by ShadyTollipop** [comment]
yeah i confirm it's still an issue

**Comment by szaaamerik** [comment]
i think its just the way adding cars works
