### ISSUE TITLE
[Feature-Request]: Modify/change Forza Credits

### ISSUE THREAD

**Issue by ribbitpoison** [ForzaMods/AIO#120]
### Game

FH5

### What feature are you requesting?

Stand provided the option to modify credits as we pleased. Unfortunately, the latest Forza update apparently made these changes go cosmetic. Is there a way to add the credits-changing feature to the AIO tool?

**Comment by szaaamerik** [comment]
**How do I get credits?**
Add cars for free using the AIO and sell them on the auction house. Adding credits directly is pretty risky so using this method will give you "clean" money that is accounted for in game.
