### ISSUE TITLE
[Bug]: not attached to FH5

### ISSUE THREAD

**Issue by Blex420** [ForzaMods/AIO#126]
### What version of the aio were you running?

0.52

### Game

FH5

### Game Version

Cracked (other) Please put the crack name/version into the issue box below

### What is the bug?

aio does not connect to fh5
can i do something wrong ?
fit-girl repack

**Comment by jimmytudesky** [comment]
Same here with FH5 1.522.259.0 and prior versions.

**Comment by WrinkleDeficit** [comment]
I believe you should be using AIO version 0.0.0.51. Try starting the AIO before running FH5.

**Comment by lmaobvobo** [comment]
@WrinkleDeficit running AIO Version 0.0.0.51 before you run the game will crash the game.

**Comment by lmaobvobo** [comment]
@Blex420 Running AIO Version 0.0.0.52 before you run the game should attach. It may take a few tries & the game may crash a couple times.

**Comment by WrinkleDeficit** [comment]
> @WrinkleDeficit running AIO Version 0.0.0.51 before you run the game will crash the game.

Sorry, my bad. Here are the steps I took that worked for me with the given FH5 version.
1. Launch Forza Horizon 5. Wait until you are at the main menu.
2. Launch AIO Version 0.0.0.51  Wait for a little bit and it should start attaching.
3. Continue to game.
