### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xClacatx** [ForzaMods/AIO#131]
### What version of the aio were you running?

0.52

### Game

FH5

### Game Version

Cracked (online-fix)

### What is the bug?

fitgirl repack updated to last version from insaneramzes, after unticking the velocity and acceleration the cars are still mod, no way to go back to regular velocity and acceleration even if closing the AIO, it needs a game restart.
when change cars in races  like Eliminator or  Open Horizon the game crashes if you didn't untick acceleration before the changing, whenever you change car before a story or event the game still crashes if didn't untick acceleration.
however, thanks for your great job (thumbs up)

**Comment by MRdoomauzz** [comment]
If you change cars after unticking the options, it fixes it

**Comment by xClacatx** [comment]
is what i said, but if you didn't untick cars game crashes, when i used AIO 0.49 it didn't happen, just tick them and it works even when changed cars, when i untick velocity and acceleration go back to normal, not in this version as i wrote upward
