### ISSUE TITLE
[Bug]: Cars not turning to free

### ISSUE THREAD

**Issue by FadyyZaky** [ForzaMods/AIO#133]
### What version of the aio were you running?

0.0.0.51

### Game

FH5

### Game Version

Cracked (other) Please put the crack name/version into the issue box below

### What is the bug?

crack: fitgirl-repacks

the mod is attached to fh5 but when I trigger free cars it doesn't turn cars in game to free

Thanks for your help

**Comment by xClacatx** [comment]
after ticking free cars need to get out of the garage/showroom and drive for few seconds then go back into showroom and it will work
