### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PX123444b** [ForzaMods/AIO#134]
### What version of the aio were you running?

0.52

### Game

FH5

### Game Version

Steam

### What is the bug?

Forza is crashing after open tool ( after Japan fh5 update )
Ins't working online and offline 
Kinda need new 0.53 AIO update

**Comment by DRIFTIN07** [comment]
i have the same problem pls help lol

**Comment by taoy330** [comment]
the same

**Comment by zzzXOA123** [comment]
请求更新 0.53版本
