### ISSUE TITLE
[Feature-Request]: 请求更新AIO修改器  谢谢！ Request an update to AIO modifier Thanks!

### ISSUE THREAD

**Issue by mryi66** [ForzaMods/AIO#137]
### Game

FH5

### What feature are you requesting?

目前地平线5 AIO功能无法使用，游戏似乎打上了新的反作弊补丁 并且更新了新的汽车 请求作者更新功能  谢谢！

Currently the Horizon 5 AIO feature is not available, the game seems to be stamped with a new anti-cheat patch and updated with a new car Request author to update the function Thank you!

并且当我打开AIO时地平线5会崩溃

And Horizon 5 crashes when I open the AIO.

**Comment by mryi66** [comment]
> ### Game
> 
> FH5
> 
> ### What feature are you requesting?
> 
> 目前地平线5 AIO功能无法使用，游戏似乎打上了新的反作弊补丁 并且更新了新的汽车 请求作者更新功能  谢谢！
> 
> Currently the Horizon 5 AIO feature is not available, the game seems to be stamped with a new anti-cheat patch and updated with a new car Request author to update the function Thank you!

并且当我打开AIO时地平线5会崩溃
And Horizon 5 crashes when I open the AIO.

**Comment by lmaobvobo** [comment]
run the game, close it, open the menu, open the game. fixed

**Comment by mryi66** [comment]
> run the game, close it, open the menu, open the game. fixed
> 

This does not open the game at all.

**Comment by kryptic-x** [comment]
> run the game, close it, open the menu, open the game. fixed

this doesn't crash it but the all cars etc doesn't work anymore meaning they've changed values or something again

**Comment by lmaobvobo** [comment]
> > run the game, close it, open the menu, open the game. fixed
> 
> this doesn't crash it but the all cars etc doesn't work anymore meaning they've changed values or something again

The easiest way to add all cars is go to autoshow/garage and select all cars and add them one by one from the car collection.

**Comment by lmaobvobo** [comment]
> > run the game, close it, open the menu, open the game. fixed
> 
> This does not open the game at all.

Which version of the game are you running?
