### ISSUE TITLE
[Bug]: AIO is very excellent 请求更新AIO修改器 谢谢！Eager hope an update to AIO modifier Thanks! 

### ISSUE THREAD

**Issue by XXOO-XiaoLiu** [ForzaMods/AIO#141]
### What version of the aio were you running?

0.0.52

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

在任何时候，无论是先启动游戏还是先启动AIO，游戏都会在AIO运行的瞬间崩溃。
At any time, whether the game is started first or AIO is started first, the game will crash at the moment of AIO operation.

**Comment by aaaaaaaaaafda** [comment]
要多久才能更新呀

**Comment by MikataV** [comment]
> How long will it take to update

I'm guessing a month or so if you're lucky. Maybe even longer. Forza devs stepped out of the hyperbolic time chamber on this update...
