### ISSUE TITLE
[Feature-Request]: Freeze Mission timer 

### ISSUE THREAD

**Issue by Hmann90** [ForzaMods/AIO#145]
### Game

FH5

### What feature are you requesting?

Thanks a lot for the great tool! It would be great, if you could add a freeze mission timer feature.
I would help a lot. Thank you in advance!

**Comment by zzzXOA123** [comment]
你的软件现在还能用？

**Comment by MikataV** [comment]
> Reference

Mine now works fine.

**Comment by MikataV** [comment]
> Does your software still work?

Mine now works fine.

**Comment by szaaamerik** [comment]
closing because this is now a v2 feature.
