### ISSUE TITLE
This is The End of Forza AIO? 

### ISSUE THREAD

**Issue by PX123444b** [ForzaMods/AIO#147]
### Game

FH5

### What feature are you requesting?

This is The End of Forza AIO?  Becuse don't get new update to long time and Aio dasn't working   
![images (1)](https://user-images.githubusercontent.com/67346358/218862724-ec6f1da5-4825-4364-9e5a-add74a0f03f8.jpg)

**Comment by Szamerik** [comment]
probably not, ethan is working on an update. also he said its mostly done but he has other things to do
