### ISSUE TITLE
[Feature-Request]: Please make AIO lactate 

### ISSUE THREAD

**Issue by TehChozinOne** [ForzaMods/AIO#148]
### Game

Both

### What feature are you requesting?

Lactate please

**Comment by zzzXOA123** [comment]
我需要AIO更下一下 现在的版本用不了




非洲人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yeethan69/AIO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 上午8:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Yeethan69/AIO] [Feature-Request]: Please make AIO lactate  (Issue #148)





 
Game
 
Both
 
What feature are you requesting?
 
Lactate please

**Comment by ItsLogic** [comment]
I agree my friend. We need AIO lactation

**Comment by szaaamerik** [comment]
I agree with ItsLogic
