### ISSUE TITLE
This hack have trojan virus!!!!!

### ISSUE THREAD

**Issue by PX123444b** [ForzaMods/AIO#150]
### What version of the aio were you running?

0.53

### Game

FH5

### Game Version

Steam

### What is the bug?

This hack have trojan virus!!!!!

**Comment by PX123444b** [comment]
Whay u do that?

**Comment by mon5termatt** [comment]
> Whay u do that [Yeethan69](https://github.com/Yeethan69) ?

It doesn't. You just don't know what a false positive is.

**Comment by mon5termatt** [comment]
Sounds like an end user error tbh.

**Comment by XXOO-XiaoLiu** [comment]
emm  funny  
you should think about why you  are  the  only  one   
  or   what's worth  hacking abou our  compuuter😂

**Comment by XXOO-XiaoLiu** [comment]
we  should have  nothing to  hacking  😂
