### ISSUE TITLE
[Bug]: Forza Mods AIO doesn't attach to FH5

### ISSUE THREAD

**Issue by ErickPhoen1x** [ForzaMods/AIO#151]
### What version of the aio were you running?

0.0.0.53 and 0.0.0.54

### Game

FH5

### Game Version

Steam

### What is the bug?

I booted up Forza Horizon 5, opened this program but it doesn't attach to FH5.
It recognizes the game as being Forza Horizon 5 but doesn't attach.
I pressed the 'Refresh' button several times and nothing happened.
I don't know what's wrong with it. The game doesn't crash but the tool doesn't do anything.
![sex](https://user-images.githubusercontent.com/126206073/221039435-12bfc086-ef02-4ba9-8f9a-9e2d01c9c9a6.PNG)

**Comment by ShamsulArifin** [comment]
following, having the same problem

**Comment by cfx2020** [comment]
maybe,you can  try running as an administrator,i success attach

**Comment by ErickPhoen1x** [comment]
Imma try it ltaer. Will update this if it works

**Comment by klxwdaniel** [comment]
same here, hopefully there is a fix for it :)

**Comment by 1979190180** [comment]
same problem，after opening the program, the fh5 will not respond

**Comment by cfx2020** [comment]
update，although i attach success ，it doesnot work，i click all cars or rare cars，no effect in the game。game version：1.553

**Comment by zzzXOA123** [comment]
0.54STEAM/微软 不能注入成功  卡在进度条 STEAM还是会崩溃

**Comment by ErickPhoen1x** [comment]
Still waiting for a fix or something. I tried running it as administrator but it didn't worked
