### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xClacatx** [ForzaMods/AIO#156]
### What version of the aio were you running?

53

### Game

FH5

### Game Version

Cracked (online-fix)

### What is the bug?

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.3-windows-x64-installer?cid=getdotnetcore
what does it means? it asks to dwnlod this to run AIO

**Comment by mon5termatt** [comment]
Means you need .net installed. How is this an AIO bug....

**Comment by XXOO-XiaoLiu** [comment]
You can understand it as updating the version of RUNTIME

**Comment by XXOO-XiaoLiu** [comment]
You can find it in the program function of the control panel
