### ISSUE TITLE
[Bug]: Forza  crash

### ISSUE THREAD

**Issue by PX123444b** [ForzaMods/AIO#159]
### What version of the aio were you running?

0.55

### Game

FH5

### Game Version

Steam

### What is the bug?

Forza is crashing after open tool ( horizon wilds update )
Ins't working online and offline

**Comment by ChaosXVerb** [comment]
Probably because the game updated today

**Comment by creeve4** [comment]
The game now uses a blacklist and will close when it detects specific programs are running.

Is there a plan to work-around this blacklist?

**Comment by FemboiFooxUwU** [comment]
> The game now uses a blacklist and will close when it detects specific programs are running.
> 
> Is there a plan to work-around this blacklist?

there probably is, but i havent been able to find one, maybe Yeethan will find a way to work around it.

**Comment by 99larmes** [comment]
: (

**Comment by Zealest** [comment]
sad, waiting for an update! :)

**Comment by hobsRKM** [comment]
> The game now uses a blacklist and will close when it detects specific programs are running.
> 
> Is there a plan to work-around this blacklist?

Yea or probably have added new anti-cheat may be kernel level. Hoping for update from AIO soon.

**Comment by szaaamerik** [comment]
> > The game now uses a blacklist and will close when it detects specific programs are running.
> > Is there a plan to work-around this blacklist?
> 
> Yea or probably have added new anti-cheat may be kernel level. Hoping for update from AIO soon.

anticheat isnt kernel level
doesnt work with fh5
