### ISSUE TITLE
Will not attach to game (Windows 10)

### ISSUE THREAD

**Issue by relentlesstech73** [ForzaMods/AIO#164]
v0.0.0.51 works fine, but this latest version (v0.0.0.55) will not attach to the game, even after clicking 'Refresh' several times.

**Comment by xClacatx** [comment]
same after latest update 563, AIO not working

**Comment by Andre-Gruby** [comment]
V0.0.0.55. - When turned on, the game crashes to the desktop,and other version too.

**Comment by szaaamerik** [comment]
doesnt work with fh5
