### ISSUE TITLE
[Bug]:  Game is crashing after new update 1.563 windows 11

### ISSUE THREAD

**Issue by hobsRKM** [ForzaMods/AIO#165]
### What version of the aio were you running?

0.0.0.5

### Game

FH5

### Game Version

Steam

### What is the bug?

Launch the game, the game itself crashes if the AIO is open. Works fine on FH4

**Comment by tssppyt** [comment]
same but I running it from the Xbox app on pc

**Comment by 9u3** [comment]
FH5 Has added a Process Blacklist which instantly closes the game if any of the processes are found. I (or anyone) do not know the list. Although I can assure you that this is in it

**Comment by shisanyue123** [comment]
Is there a workaround？

**Comment by 9u3** [comment]
Currently no. I don't know when there will be one

**Comment by trophysystm** [comment]
any update on when there will be an update

**Comment by szaaamerik** [comment]
> any update on when there will be an update

nope
