### ISSUE TITLE
AIO not attaching on SteamOS Steamdeck [Bug]: 

### ISSUE THREAD

**Issue by ezzinekaemel** [ForzaMods/AIO#166]
### What version of the aio were you running?

0.0.0.55

### Game

FH4

### Game Version

Steam

### What is the bug?

I am trying to use this on SteamOS Steamdeck with Steamtinkerlauncher.
Steamtinkerlauncher makes it so the game AND the AIO launch at the same time which causes issues with AIO attaching to the game.

Can you add a manual button to "reattch" once the game finished launching.
This is the only way to make it work on the Steamdeck.
Thank you !

**Comment by szaaamerik** [comment]
sorry for the wait, try clicking refresh in aio and see if it works, but it should matter that aio is launched along the game

**Comment by szaaamerik** [comment]
closing this as no response
