### ISSUE TITLE
Update aio for fh5

### ISSUE THREAD

**Issue by MHL-HOOMAN** [ForzaMods/AIO#168]

**Comment by trophysystm** [comment]
not working for me either, hopefully gets fixed soon

**Comment by kuyi843** [comment]
aio is not currently available,But some people still have access to all the cars,What software did they use？

**Comment by shisanyue123** [comment]
I would also like to know

**Comment by XXOO-XiaoLiu** [comment]
I guess the next update is after Adventure goes online

**Comment by 771919004** [comment]
> aio is not currently available,But some people still have access to all the cars,What software did they use？

I think they use this program for all cars - [https://www.youtube.com/watch?v=l1BGpAC7X-s](url)

But it's only for Patreon users...

**Comment by CaffNoir59** [comment]
Hi !
@771919004 do you have a working link ? The download look's deleted : https://paste.pics/NYCIR

**Comment by 771919004** [comment]
> Hi ! @771919004 do you have a working link ? The download look's deleted : https://paste.pics/NYCIR

Hi.
I uploaded it again.

**Comment by CaffNoir59** [comment]
thnaks you very much m8 !

**Comment by tipsytrucosdejuegos** [comment]
Sorry but seems not work in new FH5 update I'm patreon by the way
