### ISSUE TITLE
[Bug]: Eziriz .NET Reactor unregistered version -- This assembly won't further work

### ISSUE THREAD

**Issue by blahpunk** [ForzaMods/AIO#172]
### What version of the aio were you running?

0.54, 0.55

### Game

FH4

### Game Version

Microsoft store

### What is the bug?

Forza-Mods-AIO executable fails to start with unregistered .NET Reactor build on Windows 10 with .NET Core 7.0.3 & 7.0.4
Attempted repair install, re-install, .NET repair, reverting

EventID 1026:
`Application: Forza-Mods-AIO.exe`
`CoreCLR Version: 7.0.423.11508`
`.NET Version: 7.0.4`
`Description: The process was terminated due to an unhandled exception.`
`Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.`
` ---> System.Exception: This assembly is protected by an unregistered version of Eziriz's ".NET Reactor"! This assembly won't further work.`
`   at Forza_Mods_AIO.Filter.PoolParserFilter.IncludeBase()`
`   at .cctor()`
`   --- End of inner exception stack trace ---`

EventID 1000:
`Faulting application name: Forza-Mods-AIO.exe, version: 0.0.0.55, time stamp: 0x634eda42`
`Faulting module name: KERNELBASE.dll, version: 10.0.19041.2788, time stamp: 0x62e593d6`
`Exception code: 0xe0434352`
`Fault offset: 0x000000000002cb69`
`Faulting process id: 0x3228`
`Faulting application start time: 0x01d960f20ed15a3d`
`Faulting application path: E:\Users\Eric\Downloads\Forza-Mods-AIO.exe`
`Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll`
`Report Id: fae0926a-f601-459c-9fb8-51d1075b49e3`
`Faulting package full name: `
`Faulting package-relative application ID: `

**Comment by szaaamerik** [comment]
for fh4 use aio 0.0.0.52
