### ISSUE TITLE
[Bug]: AIO Straight up not opening

### ISSUE THREAD

**Issue by ZeraBlayde** [ForzaMods/AIO#176]
### What version of the aio were you running?

0.55

### Game

FH4

### Game Version

Steam

### What is the bug?

When I open the tool, FH4 open or not, Nothing happens after the "Do you want this app to be able to change data on your device" Warning

Thanks,

-Zera

**Comment by Humwq** [comment]
try 0.0.0.52

**Comment by sebi4** [comment]
> try 0.0.0.52

thanks dude you helped me too

**Comment by ZeraBlayde** [comment]
> try 0.0.0.52

Thanks man, worked

**Comment by L0v3craft** [comment]
> try 0.0.0.52

The version 0.0.0.52 starts but it crashes the game (tried with version 1.576.537.0). Newer versions don't start.

**Comment by szaaamerik** [comment]
> > try 0.0.0.52
> 
> The version 0.0.0.52 starts but it crashes the game (tried with version 1.576.537.0). Newer versions don't start.

doesnt work with fh5
