### ISSUE TITLE
[Bug]: the Forza-Mods-AIO.exe did not open after installing .net framework

### ISSUE THREAD

**Issue by Yourind** [ForzaMods/AIO#179]
### What version of the aio were you running?

0.0.0.55

### Game

FH5

### Game Version

Steam

### What is the bug?

the Forza-Mods-AIO.exe did not open after installing .net framework

**Comment by Samm223** [comment]
when trying to open it for me it crashes the game and still doesn't open

**Comment by hungryPotato423** [comment]
I have the same issue on windows 10 
It never opens or loads and it crashes the game at the same time 

I hope its fixed soon I really want the new cars

**Comment by vadimlitvinenko87** [comment]
same works only 52 build

**Comment by Samm223** [comment]
> same works only 52 build

i cant even get the 52 build to work even after removing old ones and the framework

**Comment by ndsamuelson** [comment]
see: https://github.com/Yeethan69/AIO/issues/182#issuecomment-1524561601

**Comment by Lynch89** [comment]
having the same problem

**Comment by nassim255** [comment]
same problem :(
