### ISSUE TITLE
opening machines

### ISSUE THREAD

**Issue by Vova123qwert** [ForzaMods/AIO#180]
Forza horizon 4, which cars can i unlock? Mclaren owen immediately gives an account ban, and forza edition machines, do they also give an account ban? and the rest, I can easily buy the Bugati Divo type, and all the rest that are given during the season.

**Comment by vadimlitvinenko87** [comment]
Owen 100% Ban, i have it thanks this tool. Car is piece of crap for info.

**Comment by Vova123qwert** [comment]
> 

I'm wondering, but the cars Which Forza edition, if they also open the ban, too, 100%?
