### ISSUE TITLE
[Bug]: Doesn't work on Windows 11.

### ISSUE THREAD

**Issue by i6l** [ForzaMods/AIO#186]
### What version of the aio were you running?

0.0.0.55

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

I had this tool before i upgrade to Windows 11 but now i try to open it doesn't pop up anything.

**Comment by i6l** [comment]
> aio doesnt work anymore dev too lazy to fix

ohh i see but does it work on windows 10 though?

**Comment by MikataV** [comment]
> aio doesnt work anymore dev too lazy to fix

LMAO its called having a life. He put this out for FREE and doesn't need to update if he doesn't want to. Its not a paid service is it.

**Comment by szaaamerik** [comment]
im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z)

**Comment by MikataV** [comment]
> im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit

Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.

**Comment by i6l** [comment]
> > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > 
> > 
> > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> 
> ehtan literally watches gay porn all day, stay mad

i mean i'm willing to pay some few bucks for him to make me some nice simple aio tool
can you ask him?

**Comment by szaaamerik** [comment]
> > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > 
> > > 
> > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > 
> > 
> > ehtan literally watches gay porn all day, stay mad
> 
> i mean i'm willing to pay some few bucks for him to make me some nice simple aio tool can you ask him?

you can use the guides on my site https://forzamods.github.io/website for free

**Comment by hobsRKM** [comment]
> > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > 
> > > 
> > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > 
> > 
> > ehtan literally watches gay porn all day, stay mad
> 
> i mean i'm willing to pay some few bucks for him to make me some nice simple aio tool can you ask him?

I saw someone pointing to this, this should work for you
https://github.com/ForzaMods/AIO/issues/182#issuecomment-1529048544

**Comment by szaaamerik** [comment]
> > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > 
> > > 
> > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > 
> > 
> > ehtan literally watches gay porn all day, stay mad
> 
> Stay mad?! lol Stop projecting sweetheart.

once you stop lying about ethan having a life lmao

**Comment by maxxed-out** [comment]
> > > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > > 
> > > > 
> > > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > > 
> > > 
> > > ehtan literally watches gay porn all day, stay mad
> > 
> > 
> > i mean i'm willing to pay some few bucks for him to make me some nice simple aio tool can you ask him?
> 
> you can use the guides on my site https://forzamods.github.io/website for free

maybe nobody trusts your crap that scans dirty and is probably a stealer or something that you have on that discord link you keep trying to get people to download

**Comment by MikataV** [comment]
> > > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > > 
> > > > 
> > > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > > 
> > > 
> > > ehtan literally watches gay porn all day, stay mad
> > 
> > 
> > Stay mad?! lol Stop projecting sweetheart.
> 
> once you stop lying about ethan having a life lmao

Hey dummy, It came from his own mouth. And you say you know him. LMAO What a little muppet are. And FYI everyone has a life, but its obvious you don't. Stay stupid.

**Comment by szaaamerik** [comment]
> > > > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > > > 
> > > > > 
> > > > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > > > 
> > > > 
> > > > ehtan literally watches gay porn all day, stay mad
> > > 
> > > 
> > > i mean i'm willing to pay some few bucks for him to make me some nice simple aio tool can you ask him?
> > 
> > 
> > you can use the guides on my site https://forzamods.github.io/website for free
> 
> maybe nobody trusts your crap that scans dirty and is probably a stealer or something that you have on that discord link you keep trying to get people to download
> 
> https://www.virustotal.com/gui/file/f8e8f2f4fb5025c5b524871c38f0f10967d408b3695a7246ee8d294b9aab61ae https://www.virustotal.com/gui/file/67f24b7810d4ed8a903cffa716dee8b3ac912c59f48560c4e38bf076d1befa48

![image](https://user-images.githubusercontent.com/126014478/236209554-a8a41837-60e4-45e6-9d58-6d9da7128120.png)
![image](https://user-images.githubusercontent.com/126014478/236209598-1201ca5e-27f3-488b-bb76-618852546057.png)


if you were smart enough to know what vmprotect is then you would know its not a virus, but yeah cry more little man. joined git 13 hours ago and doesnt know anything about recompiled cheatengines, just proves how braindead you are. if it was a virus then why would it be pinned on the forzamods discord itself? useless nobody, jump off a bridge

**Comment by szaaamerik** [comment]
> > > > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > > > 
> > > > > 
> > > > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > > > 
> > > > 
> > > > ehtan literally watches gay porn all day, stay mad
> > > 
> > > 
> > > Stay mad?! lol Stop projecting sweetheart.
> > 
> > 
> > once you stop lying about ethan having a life lmao
> 
> Hey dummy, It came from his own mouth. And you say you know him. LMAO What a little muppet are. And FYI everyone has a life, but its obvious you don't. Stay stupid.

lets just come to an agreement i dont want to argue with you anyways, the tool wont be updated anytime soon and me talking shit about ethan was a joke anyways. yes i know he has a life, he mostly does uni stuff. so as i said if you dont wanna be friends or something thats fine but i just want to stop this shit talk.

**Comment by MikataV** [comment]
> > > > > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > > > > 
> > > > > > 
> > > > > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > > > > 
> > > > > 
> > > > > ehtan literally watches gay porn all day, stay mad
> > > > 
> > > > 
> > > > Stay mad?! lol Stop projecting sweetheart.
> > > 
> > > 
> > > once you stop lying about ethan having a life lmao
> > 
> > 
> > Hey dummy, It came from his own mouth. And you say you know him. LMAO What a little muppet are. And FYI everyone has a life, but its obvious you don't. Stay stupid.
> 
> lets just come to an agreement i dont want to argue with you anyways, the tool wont be updated anytime soon and me talking shit about ethan was a joke anyways. yes i know he has a life, he mostly does uni stuff. so as i said if you dont wanna be friends or something thats fine but i just want to stop this shit talk.

Agreed.

**Comment by maxxed-out** [comment]
> > > > > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > > > > 
> > > > > > 
> > > > > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > > > > 
> > > > > 
> > > > > ehtan literally watches gay porn all day, stay mad
> > > > 
> > > > 
> > > > i mean i'm willing to pay some few bucks for him to make me some nice simple aio tool can you ask him?
> > > 
> > > 
> > > you can use the guides on my site https://forzamods.github.io/website for free
> > 
> > 
> > maybe nobody trusts your crap that scans dirty and is probably a stealer or something that you have on that discord link you keep trying to get people to download
> > https://www.virustotal.com/gui/file/f8e8f2f4fb5025c5b524871c38f0f10967d408b3695a7246ee8d294b9aab61ae https://www.virustotal.com/gui/file/67f24b7810d4ed8a903cffa716dee8b3ac912c59f48560c4e38bf076d1befa48
> 
> ![image](https://user-images.githubusercontent.com/126014478/236209554-a8a41837-60e4-45e6-9d58-6d9da7128120.png) ![image](https://user-images.githubusercontent.com/126014478/236209598-1201ca5e-27f3-488b-bb76-618852546057.png)
> 
> if you were smart enough to know what vmprotect is then you would know its not a virus, but yeah cry more little man. joined git 13 hours ago and doesnt know anything about recompiled cheatengines, just proves how braindead you are. if it was a virus then why would it be pinned on the forzamods discord itself? useless nobody, jump off a bridge

im well aware of what vmprotect is and if this is just a modified cheatengine there is no valid reasoning for using vmprotect which is just as easily detected and makes it 100 times easier for forza to kill this in the anticheat if they chose to

the only valid explanation for you doing this, sharing links to the file hosted on discord, and repeatedly demanding people download your shit is because you're hiding something dirty behind it

**Comment by hobsRKM** [comment]
> > > > > > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > > > > > 
> > > > > > > 
> > > > > > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > > > > > 
> > > > > > 
> > > > > > ehtan literally watches gay porn all day, stay mad
> > > > > 
> > > > > 
> > > > > i mean i'm willing to pay some few bucks for him to make me some nice simple aio tool can you ask him?
> > > > 
> > > > 
> > > > you can use the guides on my site https://forzamods.github.io/website for free
> > > 
> > > 
> > > maybe nobody trusts your crap that scans dirty and is probably a stealer or something that you have on that discord link you keep trying to get people to download
> > > https://www.virustotal.com/gui/file/f8e8f2f4fb5025c5b524871c38f0f10967d408b3695a7246ee8d294b9aab61ae https://www.virustotal.com/gui/file/67f24b7810d4ed8a903cffa716dee8b3ac912c59f48560c4e38bf076d1befa48
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/126014478/236209554-a8a41837-60e4-45e6-9d58-6d9da7128120.png) ![image](https://user-images.githubusercontent.com/126014478/236209598-1201ca5e-27f3-488b-bb76-618852546057.png)
> > if you were smart enough to know what vmprotect is then you would know its not a virus, but yeah cry more little man. joined git 13 hours ago and doesnt know anything about recompiled cheatengines, just proves how braindead you are. if it was a virus then why would it be pinned on the forzamods discord itself? useless nobody, jump off a bridge
> 
> im well aware of what vmprotect is and if this is just a modified cheatengine there is no valid reasoning for using vmprotect which is just as easily detected and makes it 100 times easier for forza to kill this in the anticheat if they chose to
> 
> the only valid explanation for you doing this, sharing links to the file hosted on discord, and repeatedly demanding people download your shit is because you're hiding something dirty behind it

I didn't knew this is a stealing compiled engine. Thanks for the detailed info. After this, i tried on to compile the engine. VM protection was not needed, i could still use my compiled engine without any issues. As you said something might be really going on with 999  then from that website?

**Comment by szaaamerik** [comment]
> > > > > > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > > > > > 
> > > > > > > 
> > > > > > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > > > > > 
> > > > > > 
> > > > > > ehtan literally watches gay porn all day, stay mad
> > > > > 
> > > > > 
> > > > > i mean i'm willing to pay some few bucks for him to make me some nice simple aio tool can you ask him?
> > > > 
> > > > 
> > > > you can use the guides on my site https://forzamods.github.io/website for free
> > > 
> > > 
> > > maybe nobody trusts your crap that scans dirty and is probably a stealer or something that you have on that discord link you keep trying to get people to download
> > > https://www.virustotal.com/gui/file/f8e8f2f4fb5025c5b524871c38f0f10967d408b3695a7246ee8d294b9aab61ae https://www.virustotal.com/gui/file/67f24b7810d4ed8a903cffa716dee8b3ac912c59f48560c4e38bf076d1befa48
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/126014478/236209554-a8a41837-60e4-45e6-9d58-6d9da7128120.png) ![image](https://user-images.githubusercontent.com/126014478/236209598-1201ca5e-27f3-488b-bb76-618852546057.png)
> > if you were smart enough to know what vmprotect is then you would know its not a virus, but yeah cry more little man. joined git 13 hours ago and doesnt know anything about recompiled cheatengines, just proves how braindead you are. if it was a virus then why would it be pinned on the forzamods discord itself? useless nobody, jump off a bridge
> 
> im well aware of what vmprotect is and if this is just a modified cheatengine there is no valid reasoning for using vmprotect which is just as easily detected and makes it 100 times easier for forza to kill this in the anticheat if they chose to
> 
> the only valid explanation for you doing this, sharing links to the file hosted on discord, and repeatedly demanding people download your shit is because you're hiding something dirty behind it

yeah file is hosted on forzamods discord server so i don't get your accusations, the engine draff also recompiled was with vm protect so ye. lie more man, "stealing info" fucking retard

**Comment by szaaamerik** [comment]
> > > > > > > > > im literally friends with the dev (https://prnt.sc/koNJz2jK8MnC) and i know what he does btw, he is lazy he has stated it many times (https://prnt.sc/O8asQL828iew) (https://prnt.sc/666k2Mp7gH-z) this is just an example of it. also im the owner of the forzamods site so suck shit
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Lol Am I meant to be impressed. I don't care who you are. You sound like a complete tit. My comment still stands.
> > > > > > > 
> > > > > > > 
> > > > > > > ehtan literally watches gay porn all day, stay mad
> > > > > > 
> > > > > > 
> > > > > > i mean i'm willing to pay some few bucks for him to make me some nice simple aio tool can you ask him?
> > > > > 
> > > > > 
> > > > > you can use the guides on my site https://forzamods.github.io/website for free
> > > > 
> > > > 
> > > > maybe nobody trusts your crap that scans dirty and is probably a stealer or something that you have on that discord link you keep trying to get people to download
> > > > https://www.virustotal.com/gui/file/f8e8f2f4fb5025c5b524871c38f0f10967d408b3695a7246ee8d294b9aab61ae https://www.virustotal.com/gui/file/67f24b7810d4ed8a903cffa716dee8b3ac912c59f48560c4e38bf076d1befa48
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/126014478/236209554-a8a41837-60e4-45e6-9d58-6d9da7128120.png) ![image](https://user-images.githubusercontent.com/126014478/236209598-1201ca5e-27f3-488b-bb76-618852546057.png)
> > > if you were smart enough to know what vmprotect is then you would know its not a virus, but yeah cry more little man. joined git 13 hours ago and doesnt know anything about recompiled cheatengines, just proves how braindead you are. if it was a virus then why would it be pinned on the forzamods discord itself? useless nobody, jump off a bridge
> > 
> > 
> > im well aware of what vmprotect is and if this is just a modified cheatengine there is no valid reasoning for using vmprotect which is just as easily detected and makes it 100 times easier for forza to kill this in the anticheat if they chose to
> > the only valid explanation for you doing this, sharing links to the file hosted on discord, and repeatedly demanding people download your shit is because you're hiding something dirty behind it
> 
> I didn't knew this is a stealing compiled engine. Thanks for the detailed info. After this, i tried on to compile the engine. VM protection was not needed, i could still use my compiled engine without any issues. As you said something might be really going on with 999 then from that website?

no hes just stupid and doesnt have any proof of the engine having a stealer so fake accusations, no proof just like nha with the aio

**Comment by UserDK1** [comment]
> 如果您回滚发布日期，您可以启动它，但无法在fh5上使用aio



> you can launch it if you roll back the date to release but wont be able to use aio on fh5

Which version can be started with Windows 11
