### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Bryanlee1231231231313213123** [ForzaMods/AIO#188]
### What version of the aio were you running?

0.55

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

THE GAME WILL JUST CRASH AFTER I RUN THE AIO 
I HAD INSTALLED LEASTEST FRAMEWORK
AND DISABLE ANTI VIRUS
WHAT CAN I DO?
AM I ONLY THE ONE HAS THIS PROBLEM?

**Comment by szaaamerik** [comment]
no
