### ISSUE TITLE
[Bug]: AIO Not Opening at all

### ISSUE THREAD

**Issue by ntwrite** [ForzaMods/AIO#190]
### What version of the aio were you running?

0.0.0.55

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

AIO does not open whatsoever, cannot get to main screen to see the tool it loads for a sec and doesn't open, is this proj dead?

**Comment by callum699** [comment]
please fix this for me

**Comment by callum699** [comment]
please tell me how to fix
