### ISSUE TITLE
win 11 not running [problem]: 

### ISSUE THREAD

**Issue by ityu90** [ForzaMods/AIO#194]
### What version of the aio were you running?

0.0.0.55

### Game

FH5

### Game Version

Cracked (other) Please put the crack name/version into the issue box below

### What is the bug?

The program has installed runtime-7.0.5. It has not run since. It is in the exceptions in the antivirus, but I have turned off the antivirus, but it will not start. Older version starts but then crashes the game.

Windows ver: Win 11 build: 22621.1778
Game ver: v1.573.834.0   [FitGirl Repack]

**Comment by ityu90** [comment]
szaaamerik, Why did you close the thread? The error still exists....

**Comment by szaaamerik** [comment]
closed it because its a known bug
