### ISSUE TITLE
[Bug]: Tool Not starting 

### ISSUE THREAD

**Issue by VuZeeh** [ForzaMods/AIO#196]
### What version of the aio were you running?

0.0.0.55

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

Hey when i Start the tool, nothing happends. When i start it ingame the Game will Crash but the Tool dont start

**Comment by szaaamerik** [comment]
known issue

**Comment by mccalltristan** [comment]
Do you plan to ever fix it?

**Comment by szaaamerik** [comment]
> Do you plan to ever fix it?

maybe
