### ISSUE TITLE
[Bug]: wont open, and when i open it in game it crashes forza 5

### ISSUE THREAD

**Issue by Jifn12** [ForzaMods/AIO#197]
### What version of the aio were you running?

0.0.0.55

### Game

FH5

### Game Version

Cracked (empress)

### Have i checked if the bug was reported?

No

### What is the bug?

I try to open the AIO tool but nothing comes up, and when i open it while im in Forza 5 it just crashes forza 5 and still doesnt open.

**Comment by Ponei90** [comment]
For me, this update 0.0.0.55 it won't open. I have windows 10, i disabled real time protection and don't work. For the update 0.0.0.52 I can open it without opening the game, but when I want to use the tool, then it's closing the game. Any fixes soon?

**Comment by szaaamerik** [comment]
closing because you didnt check

**Comment by Ponei90** [comment]
check what exactly? Be more specific!

**Comment by szaaamerik** [comment]
> check what exactly? Be more specific!

**Have i checked if the bug was reported? No**

please read. im closing this issue permamently now
