### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by kaplan96** [ForzaMods/AIO#198]
### What version of the aio were you running?

0.0.0.55

### Game

FH5

### Game Version

Steam

### Have i checked if the bug was reported?

Yes

### What is the bug?

open the Forza Mods AIO and game crashes. Not working mod. History 18.06.2023

**Comment by szaaamerik** [comment]
You didnt check, if you did then this issue wouldnt exist. Closing because duplicate and known

**Comment by kaplan96** [comment]
is there a working version?
