### ISSUE TITLE
[虫子]：为什么无法打开软件 并且闪退游戏

### ISSUE THREAD

**Issue by RDCKhan** [ForzaMods/AIO#199]
### What version of the aio were you running?

0.55

### Game

FH5

### Game Version

Steam

### Have i checked if the bug was reported?

No

### What is the bug?

闪退游戏并且打不开软件

**Comment by szaaamerik** [comment]
funny, because not only its invalid. also you didnt read the readme. I am closing this because its a known issue and bug report is a duplicate & invalid

有趣的是，因为它不仅是无效的，而且你也没有读过readme。我正在关闭这个问题，因为它是一个已知的问题，而且错误报告是重复的和无效的。

**Comment by RDCKhan** [comment]
> 有趣，因为它不仅无效，而且你没有阅读自述。我关闭这个是因为这是一个已知问题，错误报告是重复的和无效的>> 有趣的是，因为它不仅是无效的，而且你也没有读了readme。我正在关闭这个问题，因为它是一个已知的问题，而且错误报告是重复的和无效的。o罗马字母的第十九个> 有趣，因为它不仅无效，而且你没有阅读自述。我关闭这个是因为这是一个已知问题，错误报告是重复的和无效的>> 有趣的是，因为它不仅是无效的，而且你也没有读了readme。我正在关闭这个问题，因为它是一个已知的问题，而且错误报告是重复的和无效的。thank you bro
