### ISSUE TITLE
[Feature-Request]: Disable Music

### ISSUE THREAD

**Issue by hydratioNx99** [ForzaMods/AIO#200]
### Game

FH4

### What feature are you requesting?

toggle to disable the intro screen music, radio and so on

**Comment by szaaamerik** [comment]
intro screen music could be feasible? but the rest you can just mute ingame. whats your idea for the actual rest?

**Comment by hydratioNx99** [comment]
I mean yes... but after every restart you have to mute the radio again and you can't turn the ingame music to 0, only to 1 and it really pisses me off so I thought maybe it's possible with a mod

![ForzaHorizon4_ZtHfhIpXXu](https://github.com/ForzaMods/AIO/assets/29978081/6c35146e-7f5e-4111-b3df-df56c726d1ab)

**Comment by szaaamerik** [comment]
yeah ok I will look into that man.

**Comment by hydratioNx99** [comment]
> yeah ok I will look into that man. I didnt know, thought its like in FH5 so yeah. my bad

fh5 got that fixed?

**Comment by szaaamerik** [comment]
ok, these values are really annoying to find. I think it might not be possible

**Comment by szaaamerik** [comment]
Closing because I couldn't get around to it.
