### ISSUE TITLE
[Bug]: Mod Crashes the Game

### ISSUE THREAD

**Issue by 8190352** [ForzaMods/AIO#201]
### What version of the aio were you running?

0.55

### Game

FH5

### Game Version

Cracked (online-fix)

### Have i checked if the bug was reported?

Yes

### What is the bug?

Whenever I try to open the mod it crashes the game (if it's open) and doesn't open the window of the mod.

**Comment by Fastrace007** [comment]
How do you fix that
I have that problem

**Comment by 8190352** [comment]
> How do you fix that I have that problem

Apparently is because of an update of the game and the mod no longer works on FH5, you can use the version 0.54 on FH4 (i think that version still works) but thats all, you can check their discord for more information.
