### ISSUE TITLE
FH5 Crashing while opening AIO Tools[Bug]: 

### ISSUE THREAD

**Issue by Fastrace007** [ForzaMods/AIO#202]
### What version of the aio were you running?

0.0.0.55

### Game

FH5

### Game Version

Microsoft store

### Have i checked if the bug was reported?

Yes

### What is the bug?

Game is crashing while opening any mod(WeMod, Stand for FH5, AIO Tools) And AIO Tools Cant launch.

**Comment by szaaamerik** [comment]
your ass did not check anything. explode
