### ISSUE TITLE
[Bug]: my game closes when i open the mid menu

### ISSUE THREAD

**Issue by XENOYGZ** [ForzaMods/AIO#203]
### What version of the aio were you running?

0.046

### Game

FH5

### Game Version

Microsoft store

### Have i checked if the bug was reported?

Yes

### What is the bug?

i expected it to not close my game when i open the mod menu

**Comment by szaaamerik** [comment]
no you didnt check anything. you didnt even read the readme.
guess what that means?
invalid issue and it leads to being closed instantly.\
