### ISSUE TITLE
[Bug]: I got a trojan from this 

### ISSUE THREAD

**Issue by pixiestick10** [ForzaMods/AIO#206]
### What version of the aio were you running?

idk

### Game

FH5

### Game Version

Microsoft store

### Have i checked if the bug was reported?

Yes

### What is the bug?

it gave me a trojan and i don't think its a bug but please just make a version without it

**Comment by szaaamerik** [comment]
suuuuuuuuuuureeeeeeeeeeeeeeeeee. now show me where in the source is the trojan. the aio is opensource lol

**Comment by pixiestick10** [comment]
> suuuuuuuuuuureeeeeeeeeeeeeeeeee. now show me where in the source is the trojan. the aio is opensource lol

oh mb either way  I just got an earlier release and it didnt have one so all good.

**Comment by szaaamerik** [comment]
no releases had the virus you are claiming they have but go off I guess
