### ISSUE TITLE
[Bug]: Application can't open without internet

### ISSUE THREAD

**Issue by lcy92** [ForzaMods/AIO#207]
### What version of the aio were you running?

2.0.3.6

### Game

FH5

### Game Version

Steam

### Have i checked if the bug was reported?

Yes

### What is the bug?

The application can't open and won't report any message when my OS has no internet or access to blocked websites in China.
2.0.3.5 version worked fine.

**Comment by szaaamerik** [comment]
ok. I will add checking if user has internet. thank you for the feedback
