### ISSUE TITLE
[Bug]: AIO Error code, Does not attach

### ISSUE THREAD

**Issue by mrengland3588** [ForzaMods/AIO#208]
### What version of the aio were you running?

2.0.3.6

### Game

FH5

### Game Version

Cracked (other) Please put the crack name/version into the issue box below

### Have i checked if the bug was reported?

Yes

### What is the bug?

Fitgirl - V1.573.834.0

When i run the AIO tool in the game root it throws the following error:
<img width="163" alt="Screenshot 2024-01-01 175321" src="https://github.com/ForzaMods/AIO/assets/155401301/c39200c4-492d-4aee-a289-9b6c1e603445">

When the tool is run outside of the root folder it does not attach
<img width="612" alt="Screenshot 2024-01-01 175357" src="https://github.com/ForzaMods/AIO/assets/155401301/472edcdf-b3cb-4df2-b17d-558e922f7fe1">

Not sure if this is a bug or user error

**Comment by szaaamerik** [comment]
dont put the aio in the root folder.
launch as admin

**Comment by mrengland3588** [comment]
Thank you! That solved the issue. I assumed it was something I was doing, but could not find a Readme or instructions to run, unless i overlooked them.
