### ISSUE TITLE
[Bug]: Bugs in changing keybindings

### ISSUE THREAD

**Issue by hycpla** [ForzaMods/AIO#211]
### What version of the aio were you running?

2.0.4.2

### Game

FH5

### Game Version

Microsoft store

### Have i checked if the bug was reported?

Yes

### What is the bug?

I was trying to change handling keybindings, and whenever I pressed a key in the keyboard, it turned out to be "F22" in the GUI. I tried many keys, and got the same result. This also happened in overlay keybindings. Is it due to conflicts in key mapping or what?
![Bugs in keybinding](https://github.com/ForzaMods/AIO/assets/125075417/a22c6846-c96a-4928-a29f-23a5cb56db82)

**Comment by szaaamerik** [comment]
>Is it due to conflicts in key mapping or what
probably not. whats ur keyboard layout?

**Comment by szaaamerik** [comment]
closing because there is no response
