### ISSUE TITLE
[Bug]: Clothing horns and stuff doesn't unlock at all

### ISSUE THREAD

**Issue by TheGhost00786** [ForzaMods/AIO#218]
### What version of the aio were you running?

2.0.6.18

### Game

FH5

### Game Version

Microsoft store

### Have i checked if the bug was reported?

Yes

### What is the bug?

nothing unlocks When clicking on unlock clothes horns emotes etc

**Comment by TheGhost00786** [comment]
thank you for your all efforts

**Comment by szaaamerik** [comment]
closing this because I will just remove this non working feature, I dont have the ability to debug this anyway
