### ISSUE TITLE
[Bug]: FH4 unlock hacks set my level and credits to 0

### ISSUE THREAD

**Issue by sushiimxne** [ForzaMods/AIO#219]
### What version of the aio were you running?

2.0.6.18

### Game

FH4

### Game Version

Microsoft store

### Have i checked if the bug was reported?

Yes

### What is the bug?

I wanted to give myself credits, but just as it turns out it made my credits go to 0 and made me a level 1 player. Now i cant add myself credits or levels and im stuck with nothing

**Comment by sushiimxne** [comment]
Adding another thing: Even if i try to earn money, it instantly shoots back to 0

**Comment by segg21** [comment]
> Adding another thing: Even if i try to earn money, it instantly shoots back to 0

not sure what you're doing, but sounds like you're wishing for a ban!

give yourself cars and sell them.

**Comment by sushiimxne** [comment]
> > Adding another thing: Even if i try to earn money, it instantly shoots back to 0
> 
> not sure what you're doing, but sounds like you're wishing for a ban!
> 
> give yourself cars and sell them.

Should i keep the add credits thing on as i claim the credits?

**Comment by segg21** [comment]
> > > Adding another thing: Even if i try to earn money, it instantly shoots back to 0
> 
> > 
> 
> > not sure what you're doing, but sounds like you're wishing for a ban!
> 
> > 
> 
> > give yourself cars and sell them.
> 
> 
> 
> Should i keep the add credits thing on as i claim the credits?
> 
> EDIT: Just sold a car, no money was added after claiming the credits, still at 0 🤷 

i never edited my xp or credits, but sounds like you messed up something. possibly your credit values is in negatives but game only shows a an unsigned value of 0?

**Comment by sushiimxne** [comment]
> > > > Adding another thing: Even if i try to earn money, it instantly shoots back to 0
> > 
> > 
> > > 
> > 
> > 
> > > not sure what you're doing, but sounds like you're wishing for a ban!
> > 
> > 
> > > 
> > 
> > 
> > > give yourself cars and sell them.
> > 
> > 
> > Should i keep the add credits thing on as i claim the credits?
> > EDIT: Just sold a car, no money was added after claiming the credits, still at 0 🤷
> 
> i never edited my xp or credits, but sounds like you messed up something. possibly your credit values is in negatives but game only shows a an unsigned value of 0?

it isnt negative no, i double checked

**Comment by sushiimxne** [comment]
hello?

**Comment by szaaamerik** [comment]
closing because this is now fixed

**Comment by sushiimxne** [comment]
> closing because this is now fixed

Its not fixed but alright... ill just grind again then

**Comment by szaaamerik** [comment]
yes it is fixed. I have pushed a commit fixing that long ago, but I havent made a new release.

**Comment by sushiimxne** [comment]
> yes it is fixed. I have pushed a commit fixing that long ago, but I havent made a new release.

ah alright, thank you :)
Is the new release gonna be available soon?
