### ISSUE TITLE
[Feature-Request]: Show the exact adjustment values a player has made to a car

### ISSUE THREAD

**Issue by VitorGeovani** [ForzaMods/AIO#222]
### Game

FH5

### What feature are you requesting?

Hi, I did some tests and I loved the MOD, one thing I found very interesting was the tuning part. In one of the tests I did, I noticed that the program showed exactly the tyre pressure and gear values that I had set in the tune, but it didn't show the other settings, such as springs and other components. I did another test, this time taking a car with another player's tune, where I couldn't change it, but I already knew the tyre pressure value, for example. The program correctly shows the value of the tyre pressure that the player used, but it doesn't show everything else.

Is it possible to get the programme to display all the correct information from a tune?

**Comment by szaaamerik** [comment]
Yes its possible but no, it wont be added.
This is like stealing tunes, therefore it wont happen.
