### ISSUE TITLE
[Bug]: the mod menues (auto-show,self,etc) is gray and not working

### ISSUE THREAD

**Issue by Akuma-0** [ForzaMods/AIO#225]
### What version of the aio were you running?

2.0.7.19

### Game

FH5

### Game Version

Cracked (online-fix)

### Have i checked if the bug was reported?

Yes

### What is the bug?

the mod menues (auto-show,self,etc) is gray and not working 
I open it after the game starts and before and nothing happened I can't enter the menues

**Comment by f0x248563** [comment]
Have you solved the problem or discovered its cause? I have the same problem, it says launch FH5 even though I launched it before or after AIO.

**Comment by Akuma-0** [comment]
Thx pro I'll try it
