### ISSUE TITLE
Fast travel not free

### ISSUE THREAD

**Issue by Momentobruh64** [ForzaMods/AIO#227]
### What version of the aio were you running?

2.0.7.19

### Game

FH4

### Game Version

Microsoft store

### Have i checked if the bug was reported?

Yes

### What is the bug?

Hello, i have collected all the travel tables but after i installed the mod, the fast travel i need to pay it 10000cr it means like i didn't hit any table, extra: the cars in the autoshow are always grey and they cannot be purchased for free or add the season and unique cars

**Comment by szaaamerik** [comment]
stop posting the same garbage on my repo you posted on the discord like 99999999999999 times
