### ISSUE TITLE
[Bug]: unlock all horns not working!

### ISSUE THREAD

**Issue by DARO75** [ForzaMods/AIO#233]
### What version of the aio were you running?

2.0.7.19

### Game

FH5

### Game Version

Microsoft store

### Have i checked if the bug was reported?

Yes

### What is the bug?

Unfortunately, the horn unlock does not work.

**Comment by szaaamerik** [comment]
this wont be fixed as I dont have the ability to debug it, also you havent checked shit. it was mentioned before in #218
