### ISSUE TITLE
[Bug]: Doesn't work in FH5 (does not recognize it)

### ISSUE THREAD

**Issue by DaniG96** [ForzaMods/AIO#234]
### What version of the aio were you running?

2.0.7.19

### Game

FH5

### Game Version

Cracked (online-fix)

### Have i checked if the bug was reported?

Yes

### What is the bug?

Can't use the tool because does not recognize Forza Horizon 5 (Update 1.636.732).

**Comment by LYSt0re** [comment]
just run the game and aio as administrator both
