### ISSUE TITLE
[Bug]: how to make it work in fm8

### ISSUE THREAD

**Issue by 123sunyu** [ForzaMods/AIO#235]
### What version of the aio were you running?

2.0.7.19

### Game

FH5

### Game Version

Steam

### Have i checked if the bug was reported?

Yes

### What is the bug?

![9a0e82e077b59e8145512ec7406f8dd](https://github.com/ForzaMods/AIO/assets/97331273/b366cf6a-2a13-45ac-9d71-745a19e1f4f9)
![24a5027df450c4489a3f8092c67f46e](https://github.com/ForzaMods/AIO/assets/97331273/29c07c40-3095-4904-b93a-71ecbd2453dd)

**Comment by szaaamerik** [comment]
if youre playing fm8 on steam, you cant. I didnt implement that ~~*yet*~~
