### ISSUE TITLE
[Bug]: Forza Horizon 5 crashes after opening the AIO, and does not open if the AIO is already running

### ISSUE THREAD

**Issue by gojira12** [ForzaMods/AIO#238]
### What version of the aio were you running?

2.0.8.1

### Game

FH5

### Game Version

Steam

### Have i checked if the bug was reported?

No

### What is the bug?

After the latest FH5 Update, the game crashes when AIO is opened or doesn't start when the AIO is already running. I hope the AIO Developers acknowledge this issue as soon as possible.

**Comment by trevtrev1018** [comment]
why  is this happing

**Comment by szaaamerik** [comment]
you havent checked shit. get the fuck out of my repo

**Comment by trevtrev1018** [comment]
Damn bruh
