### ISSUE TITLE
[Bug]:  Forza crash when I open forza aio

### ISSUE THREAD

**Issue by icxdlol** [ForzaMods/AIO#239]
### What version of the aio were you running?

20.8.1 

### Game

FH5

### Game Version

Microsoft store

### Have i checked if the bug was reported?

Yes

### What is the bug?

The bug is whenever i open up forza 5 and then i open up the mods i got everything i need off and it dont work please fix this

**Comment by szaaamerik** [comment]
you havent checked shit. get the fuck out of my repo

**Comment by icxdlol** [comment]
yes i have i turned off the virus protection and i downloaded the source code

**Comment by szaaamerik** [comment]
no. you havent checked any of the bugs. if you did then this issue wouldnt exist. stop saying bullshit
