### ISSUE TITLE
[Bug]: Forza Horizon 5 crash issue is still not fixed 

### ISSUE THREAD

**Issue by gojira12** [ForzaMods/AIO#240]
### What version of the aio were you running?

2.0.8.1

### Game

FH5

### Game Version

Steam

### Have i checked if the bug was reported?

Yes

### What is the bug?

Game crashes on opening AIO, and doesn't start if AIO is already running. I've reported it before and it was closed. But it hasn't been fixed. Please fix this issue.

**Comment by gojira12** [comment]
i hope this issue is not ignored and is fixed soon

**Comment by gojira12** [comment]
its causing hinderance, please fix it 🙏🙏

**Comment by DeadlyMurk** [comment]
After updating FH5, it stopped working AIO

**Comment by gojira12** [comment]
yeah thats what the issue is

**Comment by szaaamerik** [comment]
you didnt check any of the issues. get the fuck out of my repo
