### ISSUE TITLE
Editing credits

### ISSUE THREAD

**Issue by RealIndica** [ForzaMods/AIO#6]
Just a thought because I came across something similar when reversing a mobile game.

If the credits are encrypted with xor logic you can set your credits in game to 0, then the result on the stats menu will be the xor key for finding and editing the value.

This works because `0 ^ 19283724232 = 19283724232`

I've had a look at forza in IDA and honestly its hard to find the right things to mess with haha.

Good luck

**Comment by szaaamerik** [comment]
this is unplanned.
