### ISSUE TITLE
[Error] Self-protection failed. Error code: 4

### ISSUE THREAD

**Issue by cartablanca08** [ForzaMods/AIO#69]
### What version of the aio were you running?

0.0.0.36

### Game

FH5

### Game Version

Cracked (online-fix)

### What is the bug?

It running well before March update.

Now it always give me an Error pop-up,
running it with or without Admin

![image](https://user-images.githubusercontent.com/101495214/158049149-af02fdad-4eab-4a5d-a45d-a4b670c71b53.png)

**Comment by ItsLogic** [comment]
Is your exe inside the game folder? If so move it somewhere else

**Comment by VladimirWRLD** [comment]
I have the same problem but for another game and i moved it from the game folder and it keeps giving me an error
