### ISSUE TITLE
[Bug]: The tuning sliders of certain cars are set all the way to the right every time you select one of them

### ISSUE THREAD

**Issue by Meat-Toboggan47** [ForzaMods/AIO#73]
### What version of the aio were you running?

0.0.0.39

### Game

FH4

### Game Version

Cracked (other) Please put the crack name/version into the issue box below

### What is the bug?

I am running the Dodi Repack of FH4 with the 0xdeadc0de online crack because it seemed to be the only crack provided by Dodi that works for me.

In the aio, I have enabled "All Cars", "Free Cars", and "Free Perf Upgrades". Certain cars, seemingly only those that don't have street/sport/race suspension options, cannot be tuned properly. When I buy them, the tuning sliders are set all the way to the right. I can change this and use them correctly, but if I switch to another car and switch back the sliders are set to the right again. If I upgrade the gearbox, for example, the tuning will work as expected, but only after I buy the upgrade to that part. 

This has persisted after multiple restarts of both the aio and the game. I have not done any thorough testing, but it does not appear to do this when the aio is not in use.
Edit: After checking, this same issue appears to happen in FH5

**Comment by ItsLogic** [comment]
If you have the free upgrades or quick add cars ticked while a car appears into your garage either bought or from it getting added through quick add cars it will have broken tuning
