### ISSUE TITLE
[Bug]: FH5 Discover all road crash under Microsoft PC version

### ISSUE THREAD

**Issue by DavidLanz** [ForzaMods/AIO#74]
### What version of the aio were you running?

0.0.0.40

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

I already have 3 houses, but it still crash when I check discovered all road under MS version of FH5.

**Comment by ItsLogic** [comment]
This issue actually isnt something we can fix as it is an issue with the game  handling extreme situations rather than the tool
