### ISSUE TITLE
[Bug]: Not attached to FH4/5

### ISSUE THREAD

**Issue by GhostLeader07** [ForzaMods/AIO#82]
### What version of the aio were you running?

0.43

### Game

FH5

### Game Version

Cracked (other) Please put the crack name/version into the issue box below

### What is the bug?

I'm running CODEX crack with Steam ver 1.455.709 and when i open AIO tool i'm getting "Not attached to FH4/5" i've tried everything and it won't work.

**Comment by iurinoe** [comment]
Same problem

**Comment by wefalltomorrow** [comment]
Sadly have the same issue.

**Comment by Nobody01101** [comment]
V 0.0.0.48- 0.0.0.47-0.0.0.46 aio tool
FH5 v1.444.438.0 cracked (idk which crack is used)
Not attaching to FH5 ^

AIO Tool v.0.0.0.43 - attached to FH5

**Comment by bibekmhz123** [comment]
i had the same issue but after installing new version v1.475 cracked codex 
finally after few seconds my game gets attached , i suggest you guys to install higher version cracked forza 5 or just install v1.475 game.
