### ISSUE TITLE
[Feature-Request]: Enhanced camera features

### ISSUE THREAD

**Issue by jdm-drift** [ForzaMods/AIO#99]
### Game

FH5

### What feature are you requesting?

are you able to extract the camera folder in forzahorizon5/media/camera? 

im gettin errors...trying. 
would love to change some camera behaviors to make the chase cam as a drift cam like this 
https://www.reddit.com/r/ForzaHorizon/comments/v4rsew/one_of_the_smoothest_drifts_ive_done_d/?utm_source=share&utm_medium=web2x&context=3

or can you implement such a camera feature in your mod?

**Comment by ItsLogic** [comment]
> are you able to extract the camera folder in forzahorizon5/media/camera?
No. Currently compression method 22 is uncracked. There are some camera related features planned for the tool rewrite though

**Comment by jdm-drift** [comment]
please inform me asap you got some sort of camera features added to the mod. thx

**Comment by Ponei90** [comment]
https://www.unknowncheats.me/forum/other-games/590256-forza-horizon-5-fov-menu.html

Here you have fov, if it helps

**Comment by szaaamerik** [comment]
we have fov and camera offset in the app now. closing because we dont plan on adding more
